#!/usr/bin/env ruby -w

# Returns the partial name of a line or nil if not found
def get_partial_name( file, line )
  if line =~ /=\s*render\s*\(?:partial\s*=>\s*["'](.*?)["']/
    path = $1

    if path.index( '/' )
      path = File.join( 'app/views', path )
    else
      path = File.join( File.dirname( file.path ), path )
    end

    path.gsub!( /([^\/]+)$/, '_\1')

    ( %w[erb rhtml rb haml] ).each do |ext|
      return "#{path}.#{ext}" if File.exists?( "#{path}.#{ext}" )
      return "#{path}.html.#{ext}" if File.exists?( "#{path}.html.#{ext}" )
    end
  end

  return nil
end

# Gets all the partials referenced in the file
def get_partials_from_file( file )
  file.each do |line|
    partial = get_partial_name( file, line )

    yield partial unless partial.nil?
  end
end

# Gets the files this path depends on.
def get_dependencies( path, maxdepth = 3, depth = 0 )

  deps = []

  return deps if depth == maxdepth

  File.open( path ) do |file|
    get_partials_from_file( file ) do |partial|
      deps << ( '-' * depth << partial )
      deps |= get_dependencies( partial, maxdepth, depth + 1 )
    end
  end

  return deps
end

# Gets the views that depend on this file
def get_dependencies_of( path, maxdepth = 8, depth = 1 )

  dependencies = []

  return dependencies if depth == maxdepth

  Dir.glob( "app/views/**/*.{erb,rb,rhtml,haml}").each do |file|
    File.open( file ) do |f|
      get_partials_from_file( f ) do |partial|

        # Does this partial match our file?
        if partial == path
          dependencies << ( '-' * depth << file )
          dependencies |= get_dependencies_of( file, maxdepth, depth + 1 )
        end
      end
    end
  end

  dependencies
end

# If no arguments given, give a full hierarchy tree
files = ARGV
files = Dir.glob( '**/*.{erb,html.rb,rhtml,haml}' ) if files.empty?

files.each do |file|
  # remove the ./ at the start of a filename.  Messes with the search
  file = file.sub(/^\.\//, '')
  deps = get_dependencies_of( file, maxdepth = 8 )

  if deps.empty?
    puts "#{file} has no views that depend on it"
  else
    puts "Files depending on #{file}:"
    puts deps
  end
end
